import { build } from 'vite';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
const dir=path.dirname(new URL(import.meta.url).pathname.replace(/^\/(\w:)/,'$1'));
const root=path.resolve(dir,'../..');
const accepted='d34b3927d63c66e60d68f1350d040725402a70b3';
execFileSync('git',['diff','--exit-code',accepted,'--','src','package.json','pnpm-lock.yaml','vite.config.ts'],{cwd:root});
await build({configFile:false,publicDir:false,build:{outDir:path.join(dir,'.generated'),emptyOutDir:false,minify:true,lib:{entry:path.join(dir,'client.ts'),name:'StagingPrepare',formats:['iife'],fileName:()=> 'initializer.txt'}}});
const hashes={};
for(const name of fs.readdirSync(path.join(root,'dist'),{recursive:true}).filter(n=>fs.statSync(path.join(root,'dist',n)).isFile())) hashes[name.replaceAll('\\','/')]=crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'dist',name))).digest('hex');
if(hashes['assets/index-bGRkr4ft.js']!=='930af87a99bb49d7fc0d069c2ae6fae2ca68bdc43b0ff6705d9550b7e12fc0a5')throw Error('Accepted production dist mismatch');
fs.writeFileSync(path.join(dir,'.generated/provenance.json'),JSON.stringify({accepted,hashes},null,2));
