import { expect, test, type Page } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import { canonicalData, readCanonicalState, readStoredState, seedAndReload, seedCanonicalAndReload, seedData } from './helpers/state'

const monday = new Date('2026-09-21T10:00:00+09:00')
async function settings(page: Page) {
  await page.getByRole('button', { name: '共通メニュー' }).click()
  await page.getByRole('button', { name: '設定', exact: true }).click()
}
async function top(page: Page) {
  await page.getByRole('button', { name: '共通メニュー' }).click()
  await page.getByRole('button', { name: '実施メニュー', exact: true }).click()
}
const upload = (page: Page, value: unknown) => page.getByLabel('正規バックアップを選択').setInputFiles({ name: 'safe-test-backup.json', mimeType: 'application/json', buffer: Buffer.from(typeof value === 'string' ? value : JSON.stringify(value)) })

// Only legacy starting storage is seeded. Every canonical entity in this test is created through visible controls.
test('H12 grouped real route: cutover, Exercise/setup/list/edit/back, Menu, Run/history/standard/complete/cancel/reload', async ({ page }, testInfo) => {
  test.setTimeout(60000)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.clock.install({ time: monday })
  await seedAndReload(page, seedData())
  await settings(page)
  await page.getByRole('button', { name: 'データ管理' }).click()
  await page.getByRole('button', { name: '正規データへの切替を準備' }).click()
  await page.getByRole('button', { name: '切替準備を確認' }).click()
  await page.getByLabel('表示したProfile候補を採用する').check()
  await page.getByLabel('切替後は正規データが正本であり、旧データへ自動復帰しないことを確認した').check()
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '正規データへ切替', exact: true }).click()
  await page.getByRole('button', { name: '設定を開く' }).click()
  await page.getByRole('button', { name: '種目', exact: true }).click()
  await page.getByLabel('種目名').fill('復旧ルートプレス')
  await page.getByLabel('部位（任意）').selectOption('肩')
  await expect(page.getByRole('group', { name: '計測設定' })).toBeVisible()
  await page.getByRole('button', { name: '保存して実施項目を設定' }).click()
  await expect(page.getByLabel('元種目').locator('option:checked')).toHaveText('復旧ルートプレス')
  await expect(page.getByLabel('表示名')).toHaveValue('復旧ルートプレス')
  await page.getByLabel('標準重量 (kg)').fill('20')
  await page.getByLabel('標準回数').fill('10')
  await page.getByLabel('標準セット数').fill('3')
  await page.getByLabel('シート位置').fill('4')
  await page.getByLabel('標準メモ', { exact: true }).fill('肩を下げる')
  await page.getByRole('button', { name: '実施項目を登録', exact: true }).click()
  await expect(page.getByRole('heading', { name: '設定済み実施項目' })).toBeVisible()
  await expect(page.getByLabel('標準回数')).toHaveCount(0)
  await page.getByRole('button', { name: /復旧ルートプレス.*編集/ }).click()
  await expect(page.getByLabel('標準メモ')).toHaveValue('肩を下げる')
  await page.getByRole('button', { name: '‹ 戻る' }).click()
  await expect(page.getByRole('heading', { name: '設定済み実施項目' })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('settings-list.png'), fullPage: true })
  await page.getByRole('button', { name: '週メニュー', exact: true }).click()
  await page.getByLabel('新しい週メニュー名').fill('復旧メニュー')
  await page.getByRole('button', { name: '週メニューを登録' }).click()
  for (const day of ['0', '1']) {
    await page.getByLabel('実施項目').selectOption({ label: '復旧ルートプレス' })
    await page.getByLabel('推奨曜日').selectOption(day)
    page.once('dialog', dialog => dialog.accept())
    await page.getByRole('button', { name: '実施項目を追加' }).click()
  }
  await top(page)
  await expect(page.getByText('今週の実施総数')).toContainText('0/2')
  await expect(page.getByText('今日の実施総数')).toContainText('0/1')
  await page.getByRole('button', { name: '推奨曜日表示' }).click()
  await page.getByRole('button', { name: /復旧ルートプレス/ }).click()
  await expect(page.getByText('肩を下げる', { exact: true })).toBeVisible()
  await page.getByLabel('今回メモ').fill('当回だけの記録')
  await page.getByLabel('回数', { exact: true }).fill('12')
  await page.getByLabel('変更理由（任意）').fill('標準回数を増やす')
  page.once('dialog', dialog => dialog.dismiss())
  await page.getByRole('button', { name: 'この設定を登録' }).click()
  expect((await readCanonicalState(page)).trainingItemSettingChanges).toHaveLength(1)
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'この設定を登録' }).click()
  await expect(page.getByText('標準設定を保存しました。', { exact: true })).toBeVisible()
  await expect(page.getByLabel('変更理由（任意）')).toHaveValue('')
  await page.getByRole('button', { name: 'この実施項目の設定履歴を見る' }).click()
  await expect(page.getByText('変更理由: 標準回数を増やす')).toBeVisible()
  await expect(page.getByText('当回だけの記録')).toHaveCount(0)
  await expect(page.getByText('肩を下げる')).toHaveCount(0)
  await page.getByRole('button', { name: '‹ 戻る' }).click()
  await expect(page.getByLabel('今回メモ')).toHaveValue('当回だけの記録')
  await page.screenshot({ path: testInfo.outputPath('run.png'), fullPage: true })
  // A no-op standard save must not append a reason-only history record.
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'この設定を登録' }).click()
  expect((await readCanonicalState(page)).trainingItemSettingChanges).toHaveLength(2)
  await page.getByRole('button', { name: '種目を完了' }).click()
  await expect(page.getByText('今週の実施総数')).toContainText('1/2')
  await expect(page.getByRole('heading', { name: '推奨曜日の実施項目' })).toBeVisible()
  await expect(page.getByRole('button', { name: /復旧ルートプレス/ })).toHaveCount(0)
  const stored = await readCanonicalState(page)
  expect(stored.sessions).toEqual([expect.objectContaining({ memo: '当回だけの記録', reps: 12, seat: '4' })])
  expect(stored.trainingItems).toEqual([expect.objectContaining({ standardMemo: '肩を下げる', reps: 12 })])
  await page.getByLabel('実施済も表示').check()
  await page.getByRole('button', { name: /復旧ルートプレス/ }).click()
  await expect(page.getByRole('button', { name: '種目を完了' })).toHaveCount(0)
  await page.getByRole('button', { name: '戻る', exact: true }).click()
  expect((await readCanonicalState(page)).sessions).toHaveLength(1)
  await page.getByRole('button', { name: 'カテゴリ表示', exact: true }).click()
  await expect(page.getByRole('button', { name: /復旧ルートプレス/ })).toHaveCount(2)
  await page.screenshot({ path: testInfo.outputPath('top-summary.png'), fullPage: true })
  await page.getByRole('button', { name: /復旧ルートプレス/ }).first().click()
  page.once('dialog', dialog => dialog.dismiss())
  await page.getByRole('button', { name: '9/21の実行を取り消す' }).click()
  expect((await readCanonicalState(page)).sessions).toHaveLength(1)
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '9/21の実行を取り消す' }).click()
  await expect(page.getByText('今週の実施総数')).toContainText('0/2')
  await page.reload()
  await expect(page.getByText('今週の実施総数')).toContainText('0/2')
  const reloaded = await readCanonicalState(page)
  expect(reloaded.sessions).toHaveLength(0)
  expect(reloaded.trainingItems).toEqual(stored.trainingItems)
  expect(reloaded.trainingItemSettingChanges).toEqual(stored.trainingItemSettingChanges)
})

test('H12 canonical backup preview, invalid non-destructive restore, full replacement/read-back/reload', async ({ page }, testInfo) => {
  await page.clock.install({ time: monday })
  const original = canonicalData()
  original.appliedProposalIds = ['already-applied']
  await seedCanonicalAndReload(page, original)
  await settings(page)
  await page.getByRole('button', { name: 'データ管理', exact: true }).click()
  const downloadEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: 'バックアップを作成' }).click()
  const download = await downloadEvent
  const exported = JSON.parse(await readFile((await download.path())!, 'utf8'))
  expect(exported.payload).toEqual(original)
  expect(await readCanonicalState(page)).toEqual(original)
  const legacyBefore = await readStoredState(page)
  await page.getByRole('button', { name: '‹ 戻る' }).click()
  await page.getByLabel('体重 (kg)').fill('80')
  await page.getByRole('button', { name: 'プロフィールを保存' }).click()
  await top(page)
  await page.getByRole('button', { name: '＋ 追加トレーニング', exact: true }).click()
  await page.getByRole('button', { name: /正規テストプレス/ }).click()
  await page.getByRole('button', { name: '種目を完了' }).click()
  await expect(page.getByText('今週の実施総数')).toContainText('0/2')
  await settings(page)
  const modified = await readCanonicalState(page)
  expect(modified.sessions).toHaveLength(1)
  await page.getByRole('button', { name: 'データ管理', exact: true }).click()
  for (const invalid of ['{', original, { ...exported, schemaVersion: 7 }, { ...exported, payload: { ...original, sessions: [{ id: 'bad' }] } }]) {
    await upload(page, invalid)
    await expect(page.getByRole('heading', { name: '復元できません' })).toBeVisible()
    await expect(page.getByRole('button', { name: '全データを置き換えて復元' })).toHaveCount(0)
    expect(await readCanonicalState(page)).toEqual(modified)
  }
  await upload(page, exported)
  await expect(page.getByRole('heading', { name: '復元内容の確認' })).toBeVisible()
  expect(await readCanonicalState(page)).toEqual(modified)
  await page.screenshot({ path: testInfo.outputPath('backup-preview.png'), fullPage: true })
  page.once('dialog', dialog => dialog.dismiss())
  await page.getByRole('button', { name: '全データを置き換えて復元' }).click()
  expect(await readCanonicalState(page)).toEqual(modified)
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '全データを置き換えて復元' }).click()
  await expect(page.getByRole('status')).toHaveText('復元しました。保存後の読み戻し一致を確認しました。')
  expect(await readCanonicalState(page)).toEqual(original)
  expect(await readStoredState(page)).toEqual(legacyBefore)
  await page.reload()
  await settings(page)
  await expect(page.getByLabel('体重 (kg)')).toHaveValue('66')
})

test('H12 restore read-back failure blocks stale editing and never declares success or falls back', async ({ page }) => {
  await seedCanonicalAndReload(page, canonicalData())
  await settings(page)
  await page.getByRole('button', { name: 'データ管理', exact: true }).click()
  const replacement = { ...canonicalData(), profile: { weight: 77 } }
  await upload(page, { format: 'training-check-backup', schemaVersion: 1, createdAt: '2026-09-30T01:00:00Z', payload: replacement })
  await expect(page.getByRole('heading', { name: '復元内容の確認' })).toBeVisible()
  // Failure injection is scoped to this isolated browser context and the next canonical read.
  await page.evaluate(() => {
    const originalGet = IDBObjectStore.prototype.get
    IDBObjectStore.prototype.get = function (...args) {
      if (this.name === 'canonical') { IDBObjectStore.prototype.get = originalGet; throw new Error('injected read-back failure') }
      return originalGet.apply(this, args)
    }
  })
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '全データを置き換えて復元' }).click()
  await expect(page.getByRole('alert')).toContainText('通常編集へ戻れません')
  await expect(page.getByRole('status')).toContainText('復元の成功を確認できません')
  await expect(page.locator('.header-back')).toBeDisabled()
  await expect(page.getByRole('button', { name: 'バックアップを作成' })).toHaveCount(0)
  await page.getByRole('button', { name: '保存状態を再読込' }).click()
  await settings(page)
  await expect(page.getByRole('heading', { name: '正規データの設定' })).toBeVisible()
  await expect(page.getByLabel('体重 (kg)')).toHaveValue('77')
})

test('H12 Settings retains Trainer interfaces and hides MAN helpers in release', async ({ page }, testInfo) => {
  await seedCanonicalAndReload(page, canonicalData())
  await settings(page)
  if (testInfo.project.name === 'release') {
    await expect(page.getByRole('button', { name: 'MAN用マスターを投入' })).toHaveCount(0)
    await expect(page.getByRole('button', { name: 'MAN用メニューJSONを作成' })).toHaveCount(0)
  } else await expect(page.getByRole('button', { name: 'MAN用マスターを投入' })).toBeVisible()
  await page.getByRole('button', { name: 'メニュー投入', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'メニュー投入' })).toBeVisible()
  await page.getByRole('button', { name: '‹ 戻る' }).click()
  await page.getByRole('button', { name: 'トレーニング履歴出力', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'トレーニング履歴出力' })).toBeVisible()
})

test('H13 Top displays 260 average and 2.50 ACWR from canonical snapshots, not current Master', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-09-30T12:00:00+09:00') })
  const value = canonicalData()
  value.sessions = [['2026-08-24', 100], ['2026-09-07', 300], ['2026-09-14', 400], ['2026-09-21', 500], ['2026-09-29', 9000]].map(([date, weight]) => ({
    id: String(date), trainingItemId: 'canonical-item', date, weight, reps: 1, sets: 1,
    snapshot: { exerciseId: 'canonical-exercise', exerciseName: '保存時の種目名', trainingItemDisplayName: '保存時の項目名', measureType: 'reps', weightMode: 'total' },
  }))
  await seedCanonicalAndReload(page, value)
  const summary = page.getByRole('region', { name: 'トレーニング負荷', exact: true })
  await expect(summary.getByText('260 pt', { exact: true })).toBeVisible()
  await expect(summary.getByText('2.50', { exact: true })).toBeVisible()
  await expect(summary.getByText('9,000 pt', { exact: true })).toBeVisible()
  await settings(page)
  await page.getByRole('button', { name: '種目', exact: true }).click()
  await page.getByRole('button', { name: /正規テストプレス.*編集/ }).click()
  await page.getByLabel('重量の扱い').selectOption('perSide')
  await page.getByRole('button', { name: '種目を更新' }).click()
  await top(page)
  await expect(summary.getByText('260 pt', { exact: true })).toBeVisible()
  await expect(summary.getByText('2.50', { exact: true })).toBeVisible()
})

test('H12 Run history is item-scoped and completed status resets at the configured week boundary', async ({ page }) => {
  await page.clock.install({ time: monday })
  const value = canonicalData()
  const items = value.trainingItems as Array<Record<string, unknown>>
  items.push({ ...items[0], id: 'other-item', displayName: '別項目', standardMemo: '別メモ' })
  const changes = value.trainingItemSettingChanges as Array<Record<string, unknown>>
  changes.push({ ...changes[0], id: 'other-change', trainingItemId: 'other-item', changeReason: '別項目の変更理由' })
  await seedCanonicalAndReload(page, value)
  await page.getByRole('button', { name: /正規テストプレス/ }).first().click()
  await page.getByRole('button', { name: 'この実施項目の設定履歴を見る' }).click()
  await expect(page.getByText('初回設定（削除できません）')).toHaveCount(1)
  await expect(page.getByText('変更理由: 別項目の変更理由')).toHaveCount(0)
  await page.getByRole('button', { name: '‹ 戻る' }).click()
  await page.getByRole('button', { name: '種目を完了' }).click()
  await expect(page.getByText('今週の実施総数')).toContainText('1/2')
  await page.clock.setFixedTime(new Date('2026-09-28T10:00:00+09:00'))
  await page.reload()
  await expect(page.getByText('今週の実施総数')).toContainText('0/2')
  await page.getByRole('button', { name: /正規テストプレス/ }).first().click()
  await expect(page.getByRole('button', { name: '種目を完了' })).toBeVisible()
  await expect(page.getByRole('button', { name: /の実行を取り消す/ })).toHaveCount(0)
})
