import { expect, test } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import { canonicalData, readCanonicalState, readStoredState, seedAndReload, seedCanonicalAndReload, seedData } from './helpers/state'

const monday = new Date('2026-09-21T10:00:00+09:00')

test('common menu reaches settings and the bottom navigation is absent', async ({ page }) => {
  await page.clock.install({ time: monday })
  await seedAndReload(page, seedData(0))

  await expect(page.locator('nav')).toHaveCount(0)
  await page.getByRole('button', { name: '共通メニュー' }).click()
  await page.getByRole('button', { name: '設定' }).click()
  await expect(page.getByRole('heading', { name: '設定' })).toBeVisible()
  await expect(page.getByLabel('ビルド識別子')).toHaveText(/^Build \d{4}-\d{2}-\d{2} \/ (?:[0-9a-f]{8}|local)$/)
  await page.getByRole('button', { name: '共通メニュー' }).click()
  await page.getByRole('button', { name: '実施メニュー' }).click()
  await expect(page.getByRole('heading', { name: '今週の実施メニュー' })).toBeVisible()
})

test('seeded menu item can be completed, persisted, and retained after reload', async ({ page }) => {
  await page.clock.install({ time: monday })
  await seedAndReload(page, seedData(0))

  await expect(page.getByRole('heading', { name: '今週の実施メニュー' })).toBeVisible()
  await page.getByRole('button', { name: /胸.*項目/ }).click()
  await page.getByRole('button', { name: /テストプレス/ }).click()
  await expect(page.getByRole('button', { name: '重量を1kg増やす' })).toBeVisible()
  const controls = page.locator('.weight-controls')
  await expect(controls).toHaveCount(1)
  const controlBounds = await controls.boundingBox()
  const weightBounds = await page.locator('.run-weight').boundingBox()
  expect(controlBounds).not.toBeNull()
  expect(weightBounds).not.toBeNull()
  expect(Math.round(controlBounds!.x + controlBounds!.width)).toBeGreaterThanOrEqual(Math.round(weightBounds!.x + weightBounds!.width) - 1)
  await page.getByRole('button', { name: '重量を1kg増やす' }).click()
  await page.getByRole('button', { name: '重量を0.25kg減らす' }).click()
  await expect(page.getByText('20.75 kg')).toBeVisible()
  await page.getByRole('button', { name: '種目を完了' }).click()
  await expect(page.getByText('未実施の項目はありません。')).toBeVisible()
  await page.getByRole('button', { name: '共通メニュー' }).click()
  await page.getByRole('button', { name: '実施メニュー' }).click()
  await expect(page.locator('.totals span').first()).toContainText('1/1')

  await expect.poll(async () => (await readStoredState(page)).sessions.length).toBe(1)
  await page.reload()
  await expect(page.getByText('今週の実施総数', { exact: false })).toContainText('1/1')
  expect((await readStoredState(page)).sessions).toHaveLength(1)
})

test('fixed date changes recommended display and resets the weekly completion state', async ({ page }) => {
  await page.clock.install({ time: monday })
  await seedAndReload(page, seedData(1))

  await page.getByRole('button', { name: '推奨曜日' }).click()
  await expect(page.getByText('表示する推奨日の項目はありません。')).toBeVisible()

  await page.clock.setFixedTime(new Date('2026-09-22T10:00:00+09:00'))
  await page.reload()
  await page.getByRole('button', { name: '推奨曜日' }).click()
  await page.getByRole('button', { name: /テストプレス/ }).click()
  await page.getByRole('button', { name: '種目を完了' }).click()
  await expect(page.getByText('今週の実施総数', { exact: false })).toContainText('1/1')

  await page.clock.setFixedTime(new Date('2026-09-28T10:00:00+09:00'))
  await page.reload()
  await expect(page.getByText('今週の実施総数', { exact: false })).toContainText('0/1')
})

test('backup export can restore the original state through the visible import control', async ({ page }) => {
  await page.clock.install({ time: monday })
  const original = seedData(0)
  await seedAndReload(page, original)
  await page.getByRole('button', { name: '共通メニュー' }).click()
  await page.getByRole('button', { name: '設定' }).click()
  await page.getByRole('button', { name: 'データ管理' }).click()

  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'バックアップを作成' }).click()
  const download = await downloadPromise
  const backup = await readFile(await download.path()!)

  const changed = { ...original, profile: { ...original.profile, weight: 80 } }
  await seedAndReload(page, changed)
  await page.getByRole('button', { name: '共通メニュー' }).click()
  await page.getByRole('button', { name: '設定' }).click()
  await page.getByRole('button', { name: 'データ管理' }).click()
  page.on('dialog', dialog => dialog.accept())
  await page.getByLabel('バックアップから復元').setInputFiles({ name: 'backup.json', mimeType: 'application/json', buffer: backup })
  await expect(page.getByRole('heading', { name: '設定' })).toBeVisible()
  await expect.poll(async () => (await readStoredState(page)).profile.weight).toBe(66)
})

test('canonical-authoritative runtime completes an entry and preserves a canonical-only session after reload', async ({ page }) => {
  await page.clock.install({ time: monday })
  await seedCanonicalAndReload(page, canonicalData())
  await expect(page.getByRole('heading', { name: '今週の実施メニュー' })).toBeVisible()
  await page.getByRole('button', { name: /正規テストプレス/ }).first().click()
  await page.getByRole('button', { name: '種目を完了' }).click()
  await expect.poll(async () => ((await readCanonicalState(page)).sessions as unknown[]).length).toBe(1)
  await page.reload()
  await expect(page.getByRole('heading', { name: '今週の実施メニュー' })).toBeVisible()
  expect((await readCanonicalState(page)).sessions).toHaveLength(1)
})

test('canonical settings imports a verified MenuProposal without changing the active menu', async ({ page }) => {
  await page.clock.install({ time: monday })
  await seedCanonicalAndReload(page, canonicalData())
  await page.getByRole('button', { name: '共通メニュー' }).click()
  await page.getByRole('button', { name: '設定' }).click()
  await expect(page.getByRole('heading', { name: '正規データの設定' })).toBeVisible()
  await expect(page.getByLabel('ビルド識別子')).toHaveText(/^Build \d{4}-\d{2}-\d{2} \/ (?:[0-9a-f]{8}|local)$/)
  await page.getByRole('button', { name: 'メニュー投入' }).click()
  await page.getByLabel('提案ファイルを選択').setInputFiles({
    name: 'proposal.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify({
      contractVersion: '1.0', proposalId: 'e2e-proposal-1', menu: { name: 'E2E投入メニュー' },
      entries: [{ trainingItemId: 'canonical-item', recommendedDay: 1, order: 0 }],
    })),
  })
  await expect(page.getByRole('heading', { name: '内容確認' })).toBeVisible()
  page.on('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '新しい週メニューを作成' }).click()
  await expect(page.getByRole('heading', { name: 'メニューを作成しました' })).toBeVisible()
  await expect(page.getByText('E2E投入メニュー', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '週メニューで内容を確認' }).click()
  await expect(page.getByRole('heading', { name: '正規データの設定' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'E2E投入メニュー' })).toBeVisible()
  const stored = await readCanonicalState(page)
  expect((stored.menus as Array<{ name: string }>).some(menu => menu.name === 'E2E投入メニュー')).toBe(true)
  expect(stored.activeMenuId).toBe('canonical-menu')
  expect(stored.appliedProposalIds).toEqual(['e2e-proposal-1'])
})

test('canonical settings opens snapshot-based analysis', async ({ page }) => {
  await page.clock.install({ time: monday })
  const data = canonicalData()
  data.sessions = [{
    id: 'analysis-session', trainingItemId: 'canonical-item', menuEntryId: 'canonical-entry-a', date: '2026-09-21',
    weight: 20, reps: 10, sets: 3, bodyWeight: 66,
    snapshot: {
      exerciseId: 'canonical-exercise', exerciseName: '正規テストプレス', trainingItemDisplayName: '正規テストプレス',
      measureType: 'reps', weightMode: 'total', classifications: [{ kind: 'bodyRegion', label: '胸' }],
    },
  }]
  await seedCanonicalAndReload(page, data)
  await page.getByRole('button', { name: '共通メニュー' }).click()
  await page.getByRole('button', { name: '設定' }).click()
  await page.getByRole('button', { name: '分析' }).click()
  await expect(page.getByRole('heading', { name: '分析' })).toBeVisible()
  await expect(page.getByText('● 全体', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '部位別負荷' }).click()
  await expect(page.getByText('● 胸', { exact: true })).toBeVisible()
})

test('canonical MAN master bootstrap creates approved items and displays their new IDs', async ({ page }) => {
  await page.clock.install({ time: monday })
  await seedCanonicalAndReload(page, canonicalData())
  await page.getByRole('button', { name: '共通メニュー' }).click()
  await page.getByRole('button', { name: '設定' }).click()
  await page.getByRole('button', { name: 'MAN用マスターを投入' }).click()
  await expect(page.getByRole('heading', { name: 'MAN用マスター投入' })).toBeVisible()
  page.on('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '承認済みMANマスターを投入' }).click()
  await expect(page.getByText('seed-fly / seed-item-7', { exact: true })).toBeVisible()
  const stored = await readCanonicalState(page)
  expect((stored.exercises as Array<{ name: string }>).map(value => value.name)).toEqual(expect.arrayContaining(['ペクトラルフライ（マシン）', 'サイドレイズ', 'レッグレイズ']))
  expect((stored.trainingItems as Array<{ displayName: string }>).map(value => value.displayName)).toEqual(expect.arrayContaining(['ペクトラルフライ（マシン）', 'サイドレイズ', 'レッグレイズ']))
})

test('canonical MAN bootstrap downloads an H-07 MenuProposal that imports without changing the active menu', async ({ page }) => {
  await page.clock.install({ time: monday })
  await seedCanonicalAndReload(page, canonicalData())
  await page.getByRole('button', { name: '共通メニュー' }).click()
  await page.getByRole('button', { name: '設定' }).click()
  await page.getByRole('button', { name: 'MAN用マスターを投入' }).click()
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '承認済みMANマスターを投入' }).click()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'MAN用メニューJSONを作成' }).click()
  const proposalFile = await readFile(await (await downloadPromise).path()!)
  const proposal = JSON.parse(proposalFile.toString())
  expect(proposal).toMatchObject({ contractVersion: '1.0', menu: { name: 'Android MAN確認メニュー' } })
  expect(proposal.entries).toHaveLength(3)
  expect(proposal.entries.map((entry: { order: number }) => entry.order)).toEqual([0, 1, 2])
  expect(JSON.stringify(proposal)).not.toContain('seed-item-7')

  await page.getByRole('button', { name: '設定へ戻る' }).click()
  await page.getByRole('button', { name: 'メニュー投入' }).click()
  await page.getByLabel('提案ファイルを選択').setInputFiles({ name: 'android-man-menu.json', mimeType: 'application/json', buffer: proposalFile })
  await expect(page.getByRole('heading', { name: '内容確認' })).toBeVisible()
  await page.getByLabel('内容を確認しました').check()
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '新しい週メニューを作成' }).click()
  await expect(page.getByRole('heading', { name: 'メニューを作成しました' })).toBeVisible()
  const stored = await readCanonicalState(page)
  const createdMenu = (stored.menus as Array<{ id: string; name: string }>).find(menu => menu.name === 'Android MAN確認メニュー')
  expect(createdMenu).toBeDefined()
  expect(stored.activeMenuId).toBe('canonical-menu')
  expect((stored.menuEntries as Array<{ menuId: string; trainingItemId: string; order: number }>)
    .filter(entry => entry.menuId === createdMenu!.id)
    .map(entry => entry.order)).toEqual([0, 1, 2])
})

test('explicit cutover adopts only the confirmed Profile candidate and does not copy legacy master data', async ({ page }) => {
  await page.clock.install({ time: monday })
  const legacy = { ...seedData(0), profile: { ...seedData(0).profile, height: 170, age: 40, sex: 'male' } }
  await seedAndReload(page, legacy)
  await page.getByRole('button', { name: '共通メニュー' }).click()
  await page.getByRole('button', { name: '設定' }).click()
  await page.getByRole('button', { name: 'データ管理' }).click()
  await page.getByRole('button', { name: '正規データへの切替を準備' }).click()
  await expect(page.getByText('体重: 66 kg')).toBeVisible()
  await expect(page.getByText('身長: 170 cm')).toBeVisible()
  await expect(page.getByText('年齢: 40')).toBeVisible()
  await expect(page.getByText('性別: male')).toBeVisible()
  await expect(page.getByRole('button', { name: '正規データへ切替' })).toBeDisabled()
  await page.getByRole('button', { name: '切替準備を確認' }).click()
  await expect(page.getByText('baseline / Recovery準備: 確認済み')).toBeVisible()
  await page.getByLabel('表示したProfile候補を採用する').check()
  await page.getByLabel('切替後は正規データが正本であり、旧データへ自動復帰しないことを確認した').check()
  page.on('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '正規データへ切替' }).click()
  await expect(page.getByRole('heading', { name: '今週の実施メニュー' })).toBeVisible()
  const canonical = await readCanonicalState(page)
  expect(canonical.profile).toMatchObject({ weight: 66, height: 170, age: 40, sex: 'male' })
  expect(canonical.exercises).toEqual([])
  expect(canonical.trainingItems).toEqual([])
  expect(canonical.menus).toEqual([])
  expect((await readStoredState(page)).exercises).toHaveLength(1)
})

test('visible canonical cutover route reaches menu confirmation, category projection, weekday dropdown, and run seat input', async ({ page }) => {
  await page.clock.install({ time: monday })
  await seedAndReload(page, seedData(0))
  await page.getByRole('button', { name: '共通メニュー' }).click()
  await page.getByRole('button', { name: '設定' }).click()
  await page.getByRole('button', { name: 'データ管理' }).click()
  await page.getByRole('button', { name: '正規データへの切替を準備' }).click()
  await page.getByRole('button', { name: '切替準備を確認' }).click()
  await page.getByLabel('表示したProfile候補を採用する').check()
  await page.getByLabel('切替後は正規データが正本であり、旧データへ自動復帰しないことを確認した').check()
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '正規データへ切替' }).click()

  await page.getByRole('button', { name: '設定を開く' }).click()
  await page.getByRole('button', { name: 'MAN用マスターを投入' }).click()
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '承認済みMANマスターを投入' }).click()
  await page.getByRole('button', { name: '設定へ戻る' }).click()
  await page.getByRole('button', { name: '週メニュー' }).click()
  await page.getByLabel('新しい週メニュー名').fill('MAN導線確認')
  await page.getByRole('button', { name: '週メニューを登録' }).click()
  await expect(page.getByRole('heading', { name: 'MAN導線確認' })).toBeVisible()
  await expect(page.getByRole('button', { name: '実施項目を追加' })).toBeDisabled()
  await page.getByLabel('実施項目').selectOption({ index: 1 })
  await page.getByLabel('推奨曜日').selectOption('0')
  page.once('dialog', dialog => {
    expect(dialog.message()).toContain('週メニューに追加')
    dialog.dismiss()
  })
  await page.getByRole('button', { name: '実施項目を追加' }).click()
  await expect(page.getByText('推奨：月')).toHaveCount(0)
  page.once('dialog', dialog => {
    expect(dialog.message()).toContain('週メニューに追加')
    dialog.accept()
  })
  await page.getByRole('button', { name: '実施項目を追加' }).click()
  await expect(page.getByText('推奨：月')).toBeVisible()

  await page.getByRole('button', { name: '共通メニュー' }).click()
  await page.getByRole('button', { name: '実施メニュー' }).click()
  await expect(page.getByRole('button', { name: 'カテゴリ表示' })).toHaveClass(/active/)
  await expect(page.getByText('胸', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /ペクトラルフライ/ }).click()
  await expect(page.getByLabel('シート位置')).toBeVisible()
  await page.getByLabel('シート位置').fill('3')
  await page.getByRole('button', { name: '種目を完了' }).click()
  await expect(page.getByText(/今週実施済み.*シート: 3/)).toBeVisible()
  await page.getByRole('button', { name: '推奨曜日表示' }).click()
  const weekdayTrigger = page.getByRole('button', { name: /表示する推奨曜日: 月/ })
  await expect(weekdayTrigger).toBeVisible()
  await weekdayTrigger.click()
  await expect(page.getByRole('group', { name: '推奨曜日を複数選択' })).toBeVisible()
  await expect(page.getByLabel('月')).toBeChecked()
  await page.getByLabel('火').check()
  await expect(page.getByLabel('火')).toBeChecked()
  await weekdayTrigger.click()
  await expect(page.getByRole('group', { name: '推奨曜日を複数選択' })).toHaveCount(0)
  await expect(weekdayTrigger).toHaveText(/月・火/)
})

test('canonical Exercise bodyRegion offers presets and preserves custom labels', async ({ page }) => {
  await page.clock.install({ time: monday })
  const data = canonicalData()
  ;(data.exercises as Array<{ classifications: Array<{ kind: string; label: string }> }>)[0].classifications = [{ kind: 'bodyRegion', label: '前腕' }]
  await seedCanonicalAndReload(page, data)
  await page.getByRole('button', { name: '共通メニュー' }).click()
  await page.getByRole('button', { name: '設定' }).click()
  await page.getByRole('button', { name: '種目', exact: true }).click()

  await page.getByRole('button', { name: /正規テストプレス.*編集/ }).click()
  await expect(page.getByLabel('部位（任意）')).toHaveValue('custom')
  await expect(page.getByLabel('カスタム部位')).toHaveValue('前腕')
  await page.getByRole('button', { name: '種目を更新' }).click()
  expect(((await readCanonicalState(page)).exercises as Array<{ classifications: Array<{ label: string }> }>)[0].classifications[0].label).toBe('前腕')

  await page.getByLabel('種目名').fill('標準部位E2E種目')
  await page.getByLabel('部位（任意）').selectOption('肩')
  await page.getByRole('button', { name: '種目だけ保存' }).click()
  await page.getByRole('button', { name: /標準部位E2E種目.*編集/ }).click()
  await expect(page.getByLabel('部位（任意）')).toHaveValue('肩')
  await page.getByLabel('部位（任意）').selectOption('unset')
  await page.getByRole('button', { name: '種目を更新' }).click()
  expect(((await readCanonicalState(page)).exercises as Array<{ name: string; classifications: unknown[] }>).find(value => value.name === '標準部位E2E種目')?.classifications).toEqual([])

  await page.getByLabel('種目名').fill('カスタム部位E2E種目')
  await page.getByLabel('部位（任意）').selectOption('custom')
  await page.getByLabel('カスタム部位').fill('前腕')
  await page.getByRole('button', { name: '種目だけ保存' }).click()
  await page.getByRole('button', { name: /カスタム部位E2E種目.*編集/ }).click()
  await expect(page.getByLabel('部位（任意）')).toHaveValue('custom')
  await expect(page.getByLabel('カスタム部位')).toHaveValue('前腕')
})

test('visible canonical settings route persists profile, exercise, item standards, history, and active menu', async ({ page }) => {
  const longExerciseName = 'Android MANで保存して再読込できる長い種目名のE2E確認用ダンベルプレスバリエーション'
  await page.clock.install({ time: monday })
  await seedAndReload(page, seedData(0))
  await page.getByRole('button', { name: '共通メニュー' }).click()
  await page.getByRole('button', { name: '設定' }).click()
  await page.getByRole('button', { name: 'データ管理' }).click()
  await page.getByRole('button', { name: '正規データへの切替を準備' }).click()
  await page.getByRole('button', { name: '切替準備を確認' }).click()
  await page.getByLabel('表示したProfile候補を採用する').check()
  await page.getByLabel('切替後は正規データが正本であり、旧データへ自動復帰しないことを確認した').check()
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '正規データへ切替' }).click()
  await page.getByRole('button', { name: '設定を開く' }).click()

  await page.getByLabel('体重 (kg)').fill('67')
  await page.getByRole('button', { name: 'プロフィールを保存' }).click()
  await page.getByRole('button', { name: '種目', exact: true }).click()
  await page.getByLabel('種目名').fill(longExerciseName)
  await page.getByRole('button', { name: '保存して実施項目を設定' }).click()
  await expect(page.getByLabel('元種目').locator('option:checked')).toHaveText(longExerciseName)
  await page.getByLabel('表示名').fill('未分類E2E項目')
  await page.getByLabel('標準重量 (kg)').fill('10')
  await page.getByLabel('標準回数').fill('8')
  await page.getByLabel('標準セット数').fill('2')
  await page.getByLabel('シート位置').fill('9')
  await page.getByRole('button', { name: '実施項目を登録' }).click()
  await expect(page.getByRole('button', { name: /未分類E2E項目.*編集/ })).toBeVisible()
  await page.getByRole('button', { name: /未分類E2E項目.*編集/ }).click()
  await page.getByLabel('標準回数').fill('9')
  await page.getByLabel('変更理由（任意）').fill('実導線確認')
  await page.getByRole('button', { name: '実施項目を更新' }).click()

  await page.getByRole('button', { name: '設定履歴' }).click()
  await expect(page.getByText('変更理由: 実導線確認')).toBeVisible()
  page.once('dialog', dialog => dialog.dismiss())
  await page.getByRole('button', { name: '削除' }).click()
  await expect(page.getByText('変更理由: 実導線確認')).toBeVisible()
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '削除' }).click()
  await expect(page.getByText('変更理由: 実導線確認')).toHaveCount(0)

  await page.getByRole('button', { name: '週メニュー' }).click()
  await page.getByLabel('新しい週メニュー名').fill('未分類確認メニュー')
  await page.getByRole('button', { name: '週メニューを登録' }).click()
  await page.getByLabel('実施項目').selectOption({ label: '未分類E2E項目' })
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '実施項目を追加' }).click()
  await expect(page.getByRole('button', { name: /未分類E2E項目.*任意.*外す/ })).toBeVisible()

  await page.getByRole('button', { name: '共通メニュー' }).click()
  await page.getByRole('button', { name: '実施メニュー' }).click()
  await page.getByRole('button', { name: 'カテゴリ表示' }).click()
  await expect(page.getByRole('heading', { name: '未分類' })).toBeVisible()
  await page.getByRole('button', { name: /未分類E2E項目/ }).click()
  await expect(page.getByLabel('シート位置')).toHaveValue('9')
  await expect(page.getByText('10.00 kg')).toBeVisible()
  await page.getByRole('button', { name: '‹ 戻る' }).click()

  await page.getByLabel('週メニュー').selectOption({ label: '未分類確認メニュー' })
  const activeMenuId = await page.getByLabel('週メニュー').inputValue()
  await page.reload()
  await expect(page.getByLabel('週メニュー')).toHaveValue(activeMenuId)
  await expect(page.getByText('未分類E2E項目', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '共通メニュー' }).click()
  await page.getByRole('button', { name: '設定' }).click()
  await expect(page.getByLabel('体重 (kg)')).toHaveValue('67')
  await page.getByRole('button', { name: '実施項目' }).click()
  await page.getByRole('button', { name: /未分類E2E項目.*編集/ }).click()
  await expect(page.getByLabel('標準回数')).toHaveValue('9')
  await expect(page.getByLabel('シート位置')).toHaveValue('9')
  await page.getByRole('button', { name: '種目', exact: true }).click()
  await expect(page.getByRole('button', { name: new RegExp(`${longExerciseName}.*編集`) })).toBeVisible()
})

test('canonical settings records a change reason and asks before deleting a noninitial setting history row', async ({ page }) => {
  await page.clock.install({ time: monday })
  await seedCanonicalAndReload(page, canonicalData())
  await page.getByRole('button', { name: '共通メニュー' }).click()
  await page.getByRole('button', { name: '設定' }).click()
  await page.getByRole('button', { name: '実施項目' }).click()
  await page.getByRole('button', { name: /正規テストプレス.*編集/ }).click()
  await page.getByLabel('標準重量 (kg)').fill('22.5')
  await page.getByLabel('変更理由（任意）').fill('MAN確認')
  await page.getByRole('button', { name: '実施項目を更新' }).click()
  await page.getByRole('button', { name: '設定履歴' }).click()
  await expect(page.getByText('変更理由: MAN確認')).toBeVisible()
  page.once('dialog', dialog => {
    expect(dialog.message()).toContain('設定変更履歴を削除')
    dialog.accept()
  })
  await page.getByRole('button', { name: '削除' }).click()
  await expect(page.getByText('初回設定（削除できません）')).toBeVisible()
  await expect(page.getByRole('button', { name: '削除' })).toHaveCount(0)
})
