import { openDB } from 'idb'

export type MeasureType='reps'|'time'; export type WeightMode='total'|'perSide'
export type Exercise={id:string;name:string;bodyPart:string;measureType:MeasureType;usesWeight:boolean;weightMode?:WeightMode;selfWeightRatio?:number;secondsLoadRatio?:number;archived?:boolean}
export type Category={id:string;name:string;bodyParts:string[];exerciseIds:string[];archived?:boolean}
export type Item={id:string;name:string;categoryId:string;exerciseId:string;weight?:number;reps?:number;seconds?:number;sets:number;seat?:string;memo1?:string;memo1Date?:string;memo2?:string;memo2Date?:string;archived?:boolean}
export type Menu={id:string;name:string;memo?:string;archived?:boolean};export type MenuItem={id:string;menuId:string;itemId:string;recommendedDay:number|null;archived?:boolean}
export type Session={id:string;itemId:string;menuId?:string;menuItemId?:string;date:string;weight?:number;reps?:number;seconds?:number;sets:number;weightFactor?:number;bodyWeight?:number;memo2?:string;isExtra?:boolean}
export type SettingHistory={id:string;itemId:string;date:string;weight?:number;reps?:number;seconds?:number;sets:number;seat?:string;memo1?:string}
export type Profile={weight:number;height?:number;age?:number;sex?:string;analysisStartDate:string}
export type AppData={version:4;activeMenuId:string;profile:Profile;exercises:Exercise[];categories:Category[];items:Item[];menus:Menu[];menuItems:MenuItem[];sessions:Session[];settingHistories:SettingHistory[]}
export const bodyParts=['胸','肩','背中','体幹','下半身'] as const;const uid=(x:string)=>`seed-${x}`
const raw=[['pull','プルダウン','背中','reps',1,0],['shrug','シュラッグ','背中','reps',1,1],['row-o','ロー（オーバーグリップ）','背中','reps',1,0],['row-u','ロー（アンダーグリップ）','背中','reps',1,0],['backext','バックエクステンション','背中','reps',1,0],['pullover','ストレートアーム・プルオーバー','背中','reps',1,0],['dbpress','ダンベルプレス','胸','reps',1,0],['fly','ペクトラルフライ（マシン）','胸','reps',1,0],['bench','ベンチプレス（逆手）','胸','reps',1,0],['inc','インクラインショルダープレス','肩','reps',1,0],['side','サイドレイズ','肩','reps',1,1],['bend','ダンベルサイドベント','体幹','reps',1,1],['raise','レッグレイズ','体幹','reps',0,0],['rotation','トーソローテーション','体幹','reps',1,0],['front','フロントプランク','体幹','time',0,0],['sideplank','サイドプランク','体幹','time',0,0],['legpress','レッグプレス','下半身','reps',1,0],['calf','カーフレイズ','下半身','reps',1,0],['curl','レッグカール','下半身','reps',1,0],['add','ヒップアダクション','下半身','reps',1,0],['abd','ヒップアブダクション','下半身','reps',1,0]] as const
const exercises=raw.map(([i,name,bodyPart,measure,uses,side])=>({id:uid(i),name,bodyPart,measureType:measure as MeasureType,usesWeight:Boolean(uses),weightMode:side?'perSide' as WeightMode:'total' as WeightMode,selfWeightRatio:0,secondsLoadRatio:0}))
const groups=[['chest','胸・肩',['胸','肩']],['back','背中',['背中']],['core','体幹・腕',['体幹']],['lower','下半身',['下半身']]] as const;const cats=groups.map(([i,name,parts])=>({id:uid(i),name,bodyParts:[...parts],exerciseIds:exercises.filter(e=>(parts as readonly string[]).includes(e.bodyPart)).map(e=>e.id)}))
const values:any[]=[[42.5,15,,5],[34,15,,5],[18,20,,5],[54,15,,5],[89,15,,5],[24,15,,5],[18,15,,5],[22.5,15,,5],[30,15,,3],[14,15,,5],[4,20,,5],[18,20,,5],[,10,,4],[57,15,,5],[,,30,3],[,,30,3],[115,15,,5],[125,15,,5],[42.5,15,,5],[124,15,,5],[,,,3]]
const items=exercises.map((e,n)=>{const v=values[n],c=cats.find(x=>x.exerciseIds.includes(e.id))!;return{id:uid(`item-${n}`),name:e.name,categoryId:c.id,exerciseId:e.id,weight:v[0],reps:v[1],seconds:v[2],sets:v[3]}})
const base:AppData={version:4,activeMenuId:uid('ramp'),profile:{weight:66,analysisStartDate:localDate()},exercises,categories:cats,items,menus:[{id:uid('ramp'),name:'助走トレーニング'},{id:uid('normal'),name:'通常メニュー'}],menuItems:items.map((x,n)=>({id:uid(`mi-${n}`),menuId:uid('ramp'),itemId:x.id,recommendedDay:null})),sessions:[],settingHistories:[]}
const dbPromise=openDB('training-check',4,{upgrade(db){if(!db.objectStoreNames.contains('state'))db.createObjectStore('state')}})
export async function loadData():Promise<AppData>{const db=await dbPromise,v=await db.get('state','app');if(v?.version===4)return v;if(!v?.items)return base;const es=(v.exercises??exercises).map((e:any)=>({...e,selfWeightRatio:e.selfWeightRatio??0,secondsLoadRatio:e.secondsLoadRatio??0})),cs=v.categories??cats;const xs:Item[]=v.items.map((x:any)=>{const e=es.find((z:Exercise)=>z.id===x.exerciseId)||es.find((z:Exercise)=>z.name===x.name)||exercises[0],c=cs.find((z:Category)=>z.id===x.categoryId)||cs.find((z:Category)=>z.exerciseIds.includes(e.id))||cats[0];return{...x,categoryId:c.id,exerciseId:e.id}});const menus=v.menus??base.menus;return{version:4,activeMenuId:v.activeMenuId??menus[0].id,profile:{weight:66,analysisStartDate:localDate(),...(v.profile??{})},exercises:es,categories:cs,items:xs,menus,menuItems:(v.menuItems??xs.map((x:Item,n:number)=>({id:uid(`migrate-${n}`),menuId:menus[0].id,itemId:x.id}))).map((m:any)=>({...m,recommendedDay:Array.isArray(m.recommendedDays)?(m.recommendedDays[0]??null):m.recommendedDay??null})),sessions:v.sessions??[],settingHistories:v.settingHistories??[]}}
export async function saveData(d:AppData){const db=await dbPromise;await db.put('state',d,'app')};export function localDate(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};export function weekStart(d=new Date()){const x=new Date(d);x.setDate(x.getDate()-((x.getDay()+6)%7));x.setHours(0,0,0,0);return x}
